# Copyright © 2018 Software AG, Darmstadt, Germany and/or its licensors
#
# SPDX-License-Identifier: Apache-2.0
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caching-client
  name: caching-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caching-client
  template:
    metadata:
      labels:
        app: caching-client
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: kops.k8s.io/instancegroup
#                    operator: In
#                    values:
#                      - clientnodes
      initContainers:
        - name: init-configured
          image: store/softwareag/terracotta-cluster-tool:10.3
          imagePullPolicy: Always
          args: ["status", "-n", "MyCluster", "-s", "terracotta-1-0.stripe-1", "-s", "terracotta-1-1.stripe-1", "-s", "terracotta-2-0.stripe-2", "-s", "terracotta-2-1.stripe-2"]
          env:
            - name: ACCEPT_EULA
              value: "Y"
      containers:
        - image: store/softwareag/sample-ehcache-client:10.3
          name: caching-client
          imagePullPolicy: Always
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: TERRACOTTA_SERVER_URL
              value: "terracotta-1-0.stripe-1:9410,terracotta-1-1.stripe-1:9410,terracotta-2-0.stripe-2:9410,terracotta-2-1.stripe-2:9410"
            - name: CLUSTERED_DEDICATED_SIZE
              value: "5"
            - name: CLUSTERED_DEDICATED_SIZE_UNIT
              value: "GB"
            - name: RESOURCE_POOL_SIZE
              value: "10"
            - name: RESOURCE_POOL_SIZE_UNIT
              value: "GB"
            - name: ENTRY_KEYS_SPREAD
              value: "50000"
            - name: POUNDING_INTERVAL_MS
              value: "1000"
      imagePullSecrets:
        - name: regcred