apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcdata-a
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-disks
  local:
    path: /data/tcdata-a
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta-a
              operator: Exists

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcdata-b
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-disks
  local:
    path: /data/tcdata-b
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta-b
              operator: Exists

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcdata-c
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-disks
  local:
    path: /data/tcdata-c
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta-c
              operator: Exists

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcdata-d
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-disks
  local:
    path: /data/tcdata-d
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta-d
              operator: Exists

