apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcdata-a
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/tcdata-a
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta-a
              operator: Exists

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcdata-b
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/tcdata-b
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta-b
              operator: Exists

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcdata-c
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/tcdata-c
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta-c
              operator: Exists

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tcdata-d
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/tcdata-d
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta-d
              operator: Exists

