apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmcdata
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-disks
  local:
    path: /data/tmcdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta
              operator: In
              values:
                - tmc