# Copyright © 2018 Software AG, Darmstadt, Germany and/or its licensors
#
# SPDX-License-Identifier: Apache-2.0
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: tmc
spec:
  ports:
    - name: tmc-port
      port: 9480
  type: LoadBalancer
  selector:
    app: tmc

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tmc
spec:
  selector:
    matchLabels:
      app: tmc
  serviceName: tmc
  replicas: 1
  template:
    metadata:
      labels:
        app: tmc
    spec:
      terminationGracePeriodSeconds: 10
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: terracotta
#                    operator: In
#                    values:
#                      - tmc
      containers:
        - image: store/softwareag/tmc:10.3
          name: tmc
          imagePullPolicy: Always
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: TMS_DEFAULTURL
              value: "terracotta://terracotta-1-0.stripe-1:9410,terracotta-1-1.stripe-1:9410,terracotta-2-0.stripe-2:9410,terracotta-2-1.stripe-2:9410"
          ports:
            - containerPort: 9480
          volumeMounts:
            - name: tmcdata
              mountPath: /data/tmc/
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: tmcdata
      spec:
        storageClassName: "fast-disks"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
