apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmcdata
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/tmcdata
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: terracotta
              operator: In
              values:
                - tmc