pool:
  vmImage: 'ubuntu-latest'

steps:
- task: YodLabs.VariableTasks.SetVariablesWithCredentials.SetVariablesWithCredentials@0
  displayName: 'Github auth'
  inputs:
    ConnectionName: gh-push-tc-org
    userNameVarName: U
    passwordVarName: P
- bash: |
    pwd
    ls -l $(build.sourcesDirectory)
    ls -l $(build.sourcesDirectory)/kubernetes/helm/terracotta
- task: Docker@0
  displayName: 'Generate helm package'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'alpine/helm'
    volumes: |
      $(build.sourcesDirectory)/kubernetes/helm/terracotta:/apps
    containerCommand: 'package .'
    detached: false    
- task: Docker@0
  displayName: 'Generate helm index.yaml'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'alpine/helm'
    volumes: |
      $(build.sourcesDirectory)/kubernetes/helm/terracotta:/apps
    containerCommand: 'repo index .'
    detached: false    
- bash: |
    git config --local user.name "autogen"
    git config --local user.email "autogen-noreply@no-reply.softwareag.com"
    mv $(build.sourcesDirectory)/kubernetes/helm/terracotta/*.* ./
    git status
    git checkout -f gh-pages
    git add index.yaml *.tgz
    git status
    git commit -a -m "Update repository with latest helm chart"
    git push origin gh-pages
  displayName: 'Commit Helm Charts'
