pool:
  vmImage: 'ubuntu-latest'

steps:
- task: YodLabs.VariableTasks.SetVariablesWithCredentials.SetVariablesWithCredentials@0
  displayName: 'Github auth'
  inputs:
    ConnectionName: gh-push-tc-org
    userNameVarName: U
    passwordVarName: P
- task: Docker@0
  displayName: 'Generate helm package and index.yaml'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'alpine/helm'
    volumes: |
      $(build.sourcesDirectory):/cloud-stuff/in
      $(build.binariesDirectory):/cloud-stuff/out
    containerCommand: 'cd /cloud-stuff/in/kubernetes/helm/terracotta && ls -l && helm package . && helm repo index .'
    detached: false
- bash: |
    git checkout github_pages
    git add index.yaml *.tar.gz
    git commit -a -m "Update repo"
  displayName: 'Commit Helm Charts'
