# Copyright (c) 2011-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
   - ReadWriteMany
  nfs:
    server: fs-xxxx.efs.us-east-1.amazonaws.com
    path: "/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-volume-claim
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: backups-volume
  # you can specify the storageClassName as empty string - if not kubernetes will dynamically create the volume with
  # retain delete, from the default volume, EBS gp2 in AWS
  storageClassName: ""