# Copyright (c) 2011-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.

apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-tool-backup
spec:
  template:
    metadata:
      name: cluster-tool-backup
    spec:
      containers:
      - name: cluster-tool-backup
        image: store/softwareag/terracotta-cluster-tool:10.2
        args: ["backup", "-n", "MyCluster", "-s", "terracotta-1-1:9410", "-s", "terracotta-1-2:9410", "-s", "terracotta-2-1:9410", "-s", "terracotta-2-2:9410"]
        env:
        - name: ACCEPT_EULA
          value: "Y"
      restartPolicy: OnFailure