# Copyright (c) 2011-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tmcdata
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
# you can specify the storageClassName as empty string - if not kubernetes will dynamically create the volume with
# retain delete, from the default volume, EBS gp2 in AWS
#  storageClassName: ""

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataroots-1-1
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataroots-1-2
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataroots-2-1
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataroots-2-2
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
