apiVersion: v1
kind: Service
metadata:
  name: stripe-1
  labels:
    app: stripe-1
spec:
  ports:
    - name: terracotta-port
      port: 9410
    - name: sync-port
      port: 9430
  clusterIP: None
  selector:
    app: stripe-1

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terracotta-1
spec:
  selector:
    matchLabels:
      app: stripe-1
  serviceName: stripe-1
  replicas: 2
  template:
    metadata:
      labels:
        app: stripe-1
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - stripe-1
                    - stripe-2
              topologyKey: kubernetes.io/hostname
      containers:
        - name: terracotta
          image: store/softwareag/terracotta-server:10.2
          command: ["bin/start-tc-server.sh"]
          args: ["-f", "/configs/stripe1.xml", "-n", "$(POD_NAME)"]
          imagePullPolicy: Always
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 9410
              name: terracotta-port
            - containerPort: 9430
              name: sync-port
          volumeMounts:
            - name: config-volume
              mountPath: /configs
            - name: dataroots
              mountPath: /data/dataroots
            - name: backups
              mountPath: /data/backups
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: tc-configs
  volumeClaimTemplates:
    - metadata:
        name: dataroots
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: backups
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi

---

apiVersion: v1
kind: Service
metadata:
  name: stripe-2
  labels:
    app: stripe-2
spec:
  ports:
    - name: terracotta-port
      port: 9410
    - name: sync-port
      port: 9430
  clusterIP: None
  selector:
    app: stripe-2

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terracotta-2
spec:
  selector:
    matchLabels:
      app: stripe-2
  serviceName: stripe-2
  replicas: 2
  template:
    metadata:
      labels:
        app: stripe-2
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - stripe-1
                    - stripe-2
              topologyKey: kubernetes.io/hostname
      containers:
        - name: terracotta
          image: store/softwareag/terracotta-server:10.2
          command: ["bin/start-tc-server.sh"]
          args: ["-f", "/configs/stripe2.xml", "-n", "$(POD_NAME)"]
          imagePullPolicy: Always
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 9410
              name: terracotta-port
            - containerPort: 9430
              name: sync-port
          volumeMounts:
            - name: config-volume
              mountPath: /configs
            - name: dataroots
              mountPath: /data/dataroots
            - name: backups
              mountPath: /data/backups
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: tc-configs
  volumeClaimTemplates:
    - metadata:
        name: dataroots
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: backups
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-tool
spec:
  template:
    metadata:
      name: cluster-tool
    spec:
      initContainers:
        - name: init-dns
          image: busybox
          command: ["sh", "-c", "hostnames=\"terracotta-1-0.stripe-1 terracotta-1-1.stripe-1 terracotta-2-0.stripe-2 terracotta-2-1.stripe-2\"; for hostname in $hostnames; do echo waiting for ${hostname}:9410; nc -z ${hostname} 9410; if [ $? -ne 0 ]; then exit 1; fi; done"]
      containers:
        - name: cluster-tool
          image: store/softwareag/terracotta-cluster-tool:10.2
          args: ["configure", "-n", "MyCluster", "/configs/stripe1.xml", "/configs/stripe2.xml"]
          env:
          - name: ACCEPT_EULA
            value: "Y"
          volumeMounts:
          - name: config-volume
            mountPath: /configs
          - name: license-volume
            mountPath: /licenses
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: tc-configs
        - name: license-volume
          configMap:
            name: license
      restartPolicy: OnFailure

---

apiVersion: v1
kind: Service
metadata:
  name: tmc
spec:
  ports:
  - name: tmc-port
    port: 9480
  type: LoadBalancer
  selector:
    app: tmc

---

apiVersion: v1
kind: Service
metadata:
  name: tmc-internal
  labels:
    app: tmc
spec:
  ports:
  - name: http
    port: 9889
  clusterIP: None
  selector:
    app: tmc

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tmc
spec:
  selector:
    matchLabels:
      app: tmc
  serviceName: tmc-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: tmc
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-configured
          image: store/softwareag/terracotta-cluster-tool:10.2
          args: ["status", "-n", "MyCluster", "-s", "terracotta-1-0.stripe-1", "-s", "terracotta-1-1.stripe-1", "-s", "terracotta-2-0.stripe-2", "-s", "terracotta-2-1.stripe-2"]
          imagePullPolicy: Always
          env:
          - name: ACCEPT_EULA
            value: "Y"
      containers:
        - image: store/softwareag/tmc:10.2
          name: tmc
          imagePullPolicy: Always
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: TMS_DEFAULTURL
              value: "terracotta://terracotta-1-0.stripe-1:9410,terracotta-1-1.stripe-1:9410,terracotta-2-0.stripe-2:9410,terracotta-2-1.stripe-2:9410"
          ports:
            - containerPort: 9480
          volumeMounts:
            - name: tmcdata
              mountPath: /data/tmc/
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: tmcdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: store-client
  name: store-client
spec:
  replicas: 1
  selector:
      matchLabels:
        app: store-client
  template:
    metadata:
      labels:
        app: store-client
    spec:
      initContainers:
        - name: init-configured
          image: store/softwareag/terracotta-cluster-tool:10.2
          args: ["status", "-n", "MyCluster", "-s", "terracotta-1-0.stripe-1", "-s", "terracotta-1-1.stripe-1", "-s", "terracotta-2-0.stripe-2", "-s", "terracotta-2-1.stripe-2"]
          imagePullPolicy: Always
          env:
          - name: ACCEPT_EULA
            value: "Y"
      containers:
        - image: store/softwareag/sample-tcstore-client:10.2
          name: store-client
          imagePullPolicy: Always
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: TERRACOTTA_SERVER_URL
              value: "terracotta-1-0.stripe-1:9410,terracotta-1-1.stripe-1:9410,terracotta-2-0.stripe-2:9410,terracotta-2-1.stripe-2:9410"
            - name: NUMBER_OF_RECORDS
              value: "1500000"
            - name: POUNDING_INTERVAL_MS
              value: "100"
            - name: ENTRY_VALUES_MEAN_SIZE_KB
              value: "25"
      imagePullSecrets:
        - name: regcred

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caching-client
  name: caching-client
spec:
  replicas: 1
  selector:
      matchLabels:
        app: caching-client
  template:
    metadata:
      labels:
        app: caching-client
    spec:
      initContainers:
        - name: init-configured
          image: store/softwareag/terracotta-cluster-tool:10.2
          imagePullPolicy: Always
          args: ["status", "-n", "MyCluster", "-s", "terracotta-1-0.stripe-1", "-s", "terracotta-1-1.stripe-1", "-s", "terracotta-2-0.stripe-2", "-s", "terracotta-2-1.stripe-2"]
          env:
          - name: ACCEPT_EULA
            value: "Y"
      containers:
        - image: store/softwareag/sample-ehcache-client:10.2
          name: caching-client
          imagePullPolicy: Always
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: TERRACOTTA_SERVER_URL
              value: "terracotta-1-0.stripe-1:9410,terracotta-1-1.stripe-1:9410,terracotta-2-0.stripe-2:9410,terracotta-2-1.stripe-2:9410"
            - name: CLUSTERED_DEDICATED_SIZE
              value: "5"
            - name: CLUSTERED_DEDICATED_SIZE_UNIT
              value: "GB"
            - name: RESOURCE_POOL_SIZE
              value: "10"
            - name: RESOURCE_POOL_SIZE_UNIT
              value: "GB"
            - name: ENTRY_KEYS_SPREAD
              value: "50000"
            - name: POUNDING_INTERVAL_MS
              value: "1000"
      imagePullSecrets:
        - name: regcred