# Copyright © 2018 Software AG, Darmstadt, Germany and/or its licensors
#
# SPDX-License-Identifier: Apache-2.0
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmc-pv-nfs
spec:
  capacity:
    storage: 4Gi
  storageClassName: "tmc-nfs"
  accessModes:
    - ReadWriteMany
  nfs:
    server: my.nfs-server.corp
    path: "/nfs/anthony/tmc-volume"
    readOnly: false

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataroots-pv-nfs
spec:
  capacity:
    storage: 30Gi
  storageClassName: "dataroots-nfs"
  accessModes:
    - ReadWriteMany
  nfs:
    server: my.nfs-server.corp
    path: "/nfs/anthony/dataroots-volume"
    readOnly: false

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-pv-nfs
spec:
  capacity:
    storage: 20Gi
  storageClassName: "backups-nfs"
  accessModes:
    - ReadWriteMany
  nfs:
    server: my.nfs-server.corp
    path: "/nfs/anthony/backups-volume"
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmc-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "tmc-nfs"
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataroots-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "dataroots-nfs"
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "backups-nfs"
  resources:
    requests:
      storage: 20Gi