# Copyright (c) 2011-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmc-pv-nfs
spec:
  capacity:
    storage: 4Gi
  storageClassName: "tmc-nfs"
  accessModes:
    - ReadWriteMany
  nfs:
    server: my.nfs-server.corp
    path: "/nfs/anthony/tmc-volume"
    readOnly: false

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataroots-pv-nfs
spec:
  capacity:
    storage: 30Gi
  storageClassName: "dataroots-nfs"
  accessModes:
    - ReadWriteMany
  nfs:
    server: my.nfs-server.corp
    path: "/nfs/anthony/dataroots-volume"
    readOnly: false

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-pv-nfs
spec:
  capacity:
    storage: 20Gi
  storageClassName: "backups-nfs"
  accessModes:
    - ReadWriteMany
  nfs:
    server: my.nfs-server.corp
    path: "/nfs/anthony/backups-volume"
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmc-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "tmc-nfs"
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataroots-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "dataroots-nfs"
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "backups-nfs"
  resources:
    requests:
      storage: 20Gi