{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "terracotta.fullname" . }}-configuration
  labels:
    app: {{ template "terracotta.name" . }}
    chart: {{ template "terracotta.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tc-config.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <tc-config xmlns="http://www.terracotta.org/config">
        <plugins>
            <service>
              <lease:connection-leasing xmlns:backup="http://www.terracottatech.com/config/backup-restore" xmlns:data="http://www.terracottatech.com/config/data-roots" xmlns:ohr="http://www.terracotta.org/config/offheap-resource" xmlns:lease="http://www.terracotta.org/service/lease">
                <lease:lease-length unit="seconds">60</lease:lease-length>
              </lease:connection-leasing>
            </service>
            <config>
                <ohr:offheap-resources xmlns:ohr="http://www.terracotta.org/config/offheap-resource">
                  {{- range .Values.offheaps }}
                    <ohr:resource name="{{ .name }}" unit="{{ .unit }}">{{ .size }}</ohr:resource>
                  {{- end}}
                </ohr:offheap-resources>
            </config>
            <config>
                <data:data-directories xmlns:backup="http://www.terracottatech.com/config/backup-restore" xmlns:data="http://www.terracottatech.com/config/data-roots" xmlns:ohr="http://www.terracotta.org/config/offheap-resource" xmlns:lease="http://www.terracotta.org/service/lease">
                    <data:directory name="PLATFORM" use-for-platform="true">/data/dataroots/platform</data:directory>
                    <data:directory name="dataroot-1" use-for-platform="false">/data/dataroots/dataroot-1</data:directory>
                    <data:directory name="dataroot-2" use-for-platform="false">/data/dataroots/dataroot-2</data:directory>
                </data:data-directories>
            </config>
            <service>
                <backup:backup-restore xmlns:backup="http://www.terracottatech.com/config/backup-restore" xmlns:data="http://www.terracottatech.com/config/data-roots" xmlns:ohr="http://www.terracotta.org/config/offheap-resource" xmlns:lease="http://www.terracotta.org/service/lease">
                    <backup:backup-location path="/data/backups"/>
                </backup:backup-restore>
            </service>
        </plugins>
        <servers>
        {{ range $i :=  until (int .Values.replicaCount) }}
            <server host="{{ template "terracotta.fullname" $root}}-{{ $i }}.{{ template "terracotta.fullname" $root}}" name="{{ template "terracotta.fullname" $root}}-{{ $i }}" bind="0.0.0.0">
                <logs>stdout:</logs>
                <tsa-port bind="0.0.0.0">9410</tsa-port>
                <tsa-group-port bind="0.0.0.0">9430</tsa-group-port>
            </server>
        {{ end }}
        </servers>
        <failover-priority>
          <availability/>
        </failover-priority>
    </tc-config>
