apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-tool-reconfigure
spec:
  template:
    metadata:
      name: cluster-tool-reconfigure
    spec:
      containers:
        - name: cluster-tool-reconfigure
          image: store/softwareag/terracotta-cluster-tool:10.3
          args: ["configure", "-n", "MyCluster", "/configs/stripe1.xml", "/configs/stripe2.xml"]
          env:
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: config-volume
              mountPath: /configs
            - name: license-volume
              mountPath: /licenses
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: tc-configs
        - name: license-volume
          configMap:
            name: license
      restartPolicy: OnFailure
